---
- name: Setup JavaScript/TypeScript Packages
  hosts: localhost
  become: yes

  tasks:
    - name: Include common tasks
      include_tasks: common.yaml

    - name: Load NPM packages
      include_vars: js_ts_tools.yaml

    - name: Set NVM_DIR based on XDG_CONFIG_HOME
      set_fact:
        nvm_dir: "{{ (ansible_env.XDG_CONFIG_HOME + '/nvm' | default('/home/' + ansible_env.SUDO_USER + '/.nvm'))}}"

    - name: Install global npm packages
      become: no
      shell: . {{ nvm_dir }}/nvm.sh && npm install -g {{ item }}
      args:
        executable: /bin/bash
      loop: "{{ npm_global }}"
