---
- name: Setup JavaScript/TypeScript Packages
  hosts: localhost

  tasks:
    - name: Include common tasks
      include_tasks: common.yaml

    - name: Load NPM packages
      become: no
      include_vars: js_ts_tools.yaml

    - name: Set NVM_DIR using nvm logic
      become: no
      shell: |
        if [ -z "${NVM_DIR-}" ]; then
          if [ -z "${XDG_CONFIG_HOME-}" ]; then
            printf %s "{{ '/home/' + ansible_env.SUDO_USER }}/.nvm"
          else
            printf %s "${XDG_CONFIG_HOME}/nvm"
          fi
        else
          printf %s "${NVM_DIR}"
        fi
      register: nvm_dir_output

    - name: Set NVM_DIR fact
      become: no
      set_fact:
        nvm_dir: "{{ nvm_dir_output.stdout }}"

    - name: Install global npm packages
      become: no
      shell: . {{ nvm_dir }}/nvm.sh && npm install -g {{ item }}
      args:
        executable: /bin/bash
      loop: "{{ npm_global }}"
