---
- name: Setup JavaScript/TypeScript Packages
  hosts: localhost
  become: yes

  tasks:
    - name: Include common tasks
      include_tasks: common.yaml

    - name: Load NPM packages
      include_vars: js_ts_tools.yaml

    - name: Install global npm packages
      become: no
      shell: . /home/{{ ansible_env.SUDO_USER }}/.nvm/nvm.sh && npm install -g {{ item }}
      args:
        executable: /bin/bash
      loop: "{{ npm_global }}"
